### ISSUE TITLE
Processes do not "kill itself" after termination

### ISSUE THREAD

**Issue by wuxiaohua1011** [erdos-project/pylot#134]
Hi, I am still a noob to how processes work but I know that in the original Carla, when i want to quite the client, I can just do a `ctrl+c` in the terminal that i am running the client. 

I did the same thing here, and although the ERDOS/Pylot process did end, the Pygame window does not close.

I've also looked in to my GPU using `nvidia-smi`, it seems like python is also still running. Is there anyways to "chain up" the termination command? 

![Screenshot from 2020-07-22 19-25-53](https://user-images.githubusercontent.com/17909837/88247167-a2903b00-cc51-11ea-848f-99a0764b7d12.png)

I'd like to mention that this is NOT an issue in the docker version, just the manual install version

Best,
Michael

**Comment by ICGog** [comment]
You can kill them with `pkill --signal 9 -f  pylot.py`. Alternatively, you can update ERDOS & Pylot to the latest commit to get Pylot to gracefully shutdown on sigint.

**Comment by JCSadeghi** [comment]
I am finding on the latest commit on master this issue is still occurring. I would be grateful if someone could confirm if they are also having this issue or if I have a problem with my setup (running in the docker container). For my application it would be nicer if I didn't have to use pkill as suggested by @ICGog

**Comment by grefffin** [comment]
May I ask if you have solved this problem? I'm also confused about this issue，thanks

**Comment by JCSadeghi** [comment]
If I remember correctly, I didn't find any solution and had to forcefully kill the processes

**Comment by grefffin** [comment]
sad，thank you~
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Jonathan&nbsp;Sadeghi"; 
Date: 2025年3月2日(星期天) 凌晨1:25
To: "erdos-project/pylot"; 
Cc: ***@***.***>; "Comment"; 
Subject: Re: [erdos-project/pylot] Processes do not &quot;kill itself&quot; after termination (#134)

&nbsp;
   
If I remember correctly, I didn't find any solution and had to forcefully kill the processes

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  JCSadeghi left a comment (erdos-project/pylot#134)
 
If I remember correctly, I didn't find any solution and had to forcefully kill the processes
