### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by anupamsobti** [erdos-project/pylot#171]
Hi

I have a few questions. Please excuse me if I'm missing something obvious:
1. What is a good way to exit from the simulator?
2. Every time I run, I start from a different location. Is there a way to fix the world parameters for a particular route? (I'm trying to evaluate one of the pieces of the pipeline. So I need the rest of the parameters to remain the same.)
3. Is there a notion of speed limits or obstacle density that can be varied?

Thanks!

**Comment by ICGog** [comment]
1. I usually just send sigint (Ctrl-C) to the simulator or I run pkill.
2. Yes, you can control your start location by setting `--simulator_spawn_point_index` ([see](https://github.com/erdos-project/pylot/blob/master/pylot/simulation/flags.py#L60)).
3. Our agent does not respect speed limits, and instead it aims to drive at a pre-specified target speed. You can change the target speed of the ego vehicle by modifying the `--target_speed` flag value ([see](https://github.com/erdos-project/pylot/blob/13bf040277c39ab967f685ec275031fd02289443/pylot/planning/flags.py#L8)). However, this won't change the driving speeds of other agents.
4. You can control the obstacle density by changing `--simulator_num_vehicles` and `--simulator_num_people` ([see](https://github.com/erdos-project/pylot/blob/master/pylot/simulation/flags.py#L49)). However, please note that large values will significantly slown down the simulator. In case you also want the other agents to be spawned in deterministic locations, please specify a value for the `--random_seed` flag. This ensures that vehicles are deterministically spawned (pedestrians are not deterministic because of this issue (https://github.com/erdos-project/pylot/issues/129)).

Please feel free to re-open this issue if you have further questions.
