### ISSUE TITLE
Planner Evaluation Metrics & Flag Parameter

### ISSUE THREAD

**Issue by yanmiao2** [erdos-project/pylot#206]
Hi developers, I have 2 questions about pylot:
1. Does pylot already provide a way to log metrics about Planner accuracy? (Like the [prediction_eval_operator.py](https://github.com/erdos-project/pylot/blob/master/pylot/prediction/linear_predictor_operator.py) for Prediction) If not, any suggestion as how to do that?

2. I specify the `num_waypoints_ahead` in [planning_flag.py](https://github.com/erdos-project/pylot/blob/master/pylot/planning/flags.py) as 60, but sometimes I can see different number(84, 120, 124...) waypoints in the output of the planner. Did i miss anything here?

**Comment by ICGog** [comment]
Hi @yanmiao2 ,

1. We do not currently log metrics about planner accuracy, but maybe the control metrics we're logging can help you (https://github.com/erdos-project/pylot/blob/master/pylot/control/control_eval_operator.py). If you have some planning metrics in mind, we would be happy to guide you on how to add them to Pylot. Can you please detail what planning metrics you're thinking of?
2.  `num_waypoints_behind` and `num_waypoints_ahead` are used to slice how many waypoints Pylot passes to the core planning algorithms (see an example [here](https://github.com/erdos-project/pylot/blob/388d4f77ffc12051cbc2e5966120089dba9d4138/pylot/planning/frenet_optimal_trajectory/fot_planner.py#L122)). However, this flag doesn't affect how many waypoints the planner will output because that depends on the algorithm the planner uses. For example, the Frenet Optimal Trajectory planner computes a waypoint for every [delta time](https://github.com/erdos-project/pylot/blob/388d4f77ffc12051cbc2e5966120089dba9d4138/pylot/planning/frenet_optimal_trajectory/flags.py#L10), and thus might return a variable number of waypoints depending on how far in time it is planning for (between `--mint` and `--maxt`).
